services:
  redis:
    image: redis:8.10.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      # Tailor this path to your system.
      - ${HOME}/Desktop/Donat/id/redis-data:/data
    networks:
      - message-board-network

  message-board:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-board
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - message-board-network

networks:
  message-board-network:
    driver: bridge
